name: Unit Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t esp_challenge .

      - name: Run unit tests
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/challenge" \
            -w /challenge/part3_unit_tests \
            esp_challenge \
            bash run.sh
